print ('================== Desafio 2 ======================')
dia = input ('Em que DIA você nasceu? ')
mes = input ('Agora, me diga o MÊS você nasceu? ')
ano = input ('E por fim, em que ANO você nasceu? ')
print ('Você nasceu no dia', dia, 'de', mes, 'de', ano, '.', 'Certo?')
